site_name: Bambusrollstuhl – Bauanleitung
site_description: Open-Source Bauanleitung & Community-Builds
site_url: https://Jan-Schubak.github.io/   # bei Project Pages
repo_url: https://github.com/Jan-Schuback/Jan-Schuback
repo_name: Jan-Schuback/Jan-Schuback

theme:
  name: material
  language: de
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy

nav:
  - Start: index.md
  - Anleitung: instructions.md
  - Downloads: downloads.md
  - Community:
      - GitHub Discussions: https://github.com/DEINNAME/DEINREPO/discussions

markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search
